sudo: flase

env:
  matrix:
    - PYTHON_VERSION: 3.5

install:
- wget https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py -O condaci.py
- python condaci.py setup

script:
- ~/miniconda/bin/python condaci.py build ./conda

notifications:
  email:
    recipients:
      - jlaura@usgs.gov
      
after_success:
