language:
  - cpp

branches:
  only:
    master


matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: g++-5
      env: GCC_VERSION=5 PYTHON_VERSION="3.5"
    - os: osx
      compiler: clang
      env: PYTHON_VERSION="3.5"

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version

install:
# We do this conditionally because it saves us some downloading if the
# version is the same.
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    if [ "$PYTHON_VERSION" == "2.7" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  else
      if ["$PYTHON_VERSION" == "2.7"]; then
      curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    else
      curl -o miniconda.sh  https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh;
    fi
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a

# Prep to build for upload to binstar
- conda install anaconda-client anaconda-build
- conda config --add channels conda-forge

# Straight from the menpo team
- if [["$TRAVIS_OS_NAME" == "osx"]]; then
    curl -o condaci.py https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py;
  else
    wget https://raw.githubusercontent.com/menpo/condaci/v0.4.8/condaci.py -O condaci.py;
  fi

- python condaci.py setup

script:
- python condaci.py build ./conda

notifications:
  email:
    recipients:
      - jlaura@usgs.gov
      
after_success:

