package:
  name: opencv3
  version: 3.1.0

source:
  git_url: https://github.com/opencv/opencv
  git_rev: 4f7b3e8a56d0492057508d9841bfd7c3be81f730

  patches:
    - cap_mpjpeg_decoder.patch  # [win]

requirements:
  build:
   - python
   - cmake  # [win]
   - hdf5 1.8.*  # [osx]
   - numpy >=1.10
   - eigen 3.*
   - tbb  # [osx]
   - msinttypes r26  # [win]

  run:
   - python
   - numpy >=1.1
   - hdf5 1.8.*  # [osx]
   - tbb   # [osx]

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD

