package:
  name: opencv3
  version: 3.1.0

source:
  git_url: https://github.com/opencv/opencv

  patches:
    - cap_mpjpeg_decoder.patch  # [win]
    - no_rpath.patch


requirements:
  build:
   - python
   - cmake  # [win]
   - hdf5 1.8.*  # [osx]
   - numpy >= 1.10
   - eigen 3.*
   - tbb  # [osx]
   - msinttypes r26  # [win]

  run:
   - python
   - numpy >= 1.10
   - hdf5 1.8.*  # [osx]
   - tbb   # [osx]

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD

