package:
  name: opencv3
  version: 3.0.0

source:
  git_url: https://github.com/Itseez/opencv.git
  git_rev: fef7509eed59567c3e3ac52d5b1efd42ddb3af3e
 
  patches:
    - python3.patch  # [win and py34]
    - python2.patch  # [win and py27]
    

requirements:
  build:
   - python
   - cmake  # [win]
   - numpy
   - eigen
   - tbb  # [osx]
   - msinttypes r26  # [win]

  run:
   - python
   - numpy
   - tbb   # [osx]

test:
  imports:
    - cv2
    - cv2.xfeatures2d

about:
  home: http://opencv.org/
  license: BSD

